spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: Smzzj17!?27
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8081
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)